config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :homes, only: [:top]
  resources :users, only: [:show,:edit,:update,:index]
  resources :books do
    resource:favorites,only:[:create,:destroy]
    resources:book_comments,only:[:create,:destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many:book_comments,dependent: :destroy
  has_many:favorites,dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id:user.id).exists?
  end
  validates :title, presence:true
  validates :body, presence:true,length:{ maximum:200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to:user
  belongs_to:book
  validates_uniqueness_of :book_id,scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments,dependent: :destroy
  has_many :favorites,dependent: :destroy
  attachment :profile_image
  validates :name,presence:true,uniqueness: true,length: { minimum: 2, maximum: 20 }
  validates :introduction ,length: { maximum:50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
      if current_user
        flash[:notice] = "Signed in successfully."
        user_path(current_user)
      end
  end
  def after_sign_up_path_for(resource)
      if user
      flash[:notice] = "Welcome! You have signed up successfully."
      end
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name ,:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end
  def destroy
    BookComment.find_by(id: params[:id],book_id:params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @book.user_id = current_user.id
      @books = Book.all
      flash[:notice] = "new book create error"
      render :index
    end

  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "You have updated book successfully."
       redirect_to book_path(@book)
    else
      flash[:notice] = "update aciton error"
      render :edit
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def destroy
    @books = Book.find(params[:id])
    @books.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit( :title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id:book.id)
    favorite.save
    redirect_to request.referer
  end
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books.all
  end

  def edit
   @user = User.find(params[:id])
   if @user != current_user
      redirect_to user_path(current_user)
   end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def index
    @book = Book.new
    @user = User.new
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container mx-auto">
  <div class="row">
    <div class="container col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0">
      <h1>Editing Book</h1>
  <div class="form-body p-4 ">
    <% if @book.errors.any? %>
          <%= @book.errors.count %>errors
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= form_with model: @book, local:true do |f| %>
        <h3>Title</h3>
          <div class="input-group">
          <%= f.text_field :title, class:"form-control", placeholder:"title" %>
          </div>
        <h3>Opinion</h3>
          <%= f.text_area :body, class:"form-control", placeholder:"body" %>
          <hr>
          <div>
            <%= f.submit 'Update Book', class:"mt-3 btn btn-lg btn-block btn-dark mt-4" %>
          </div>
        <% end %>
      </div>
  <%= link_to "Show" ,book_path(@book) %>
  |
  <%= link_to "Back" ,books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if flash[:notice]%>
  <%= flash[:notice] %>
<% end %>
<% if @book.errors.any? %>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--ログインしているユーザーの一覧情報-->
    <div class="col-md-3 col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag current_user, :profile_image,:fill,100,100,fallback:"noimage.png",size:"100x100"%>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= current_user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= current_user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <button type="button" class="btn btn-outline-primary btn-block">
          <%= link_to edit_user_path(current_user), class: 'nav-link', method: :get do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </button>
      </div>
      <h2 class="mt-3">New book</h2>
      <!--あとで修正をする-->
      <%= form_with model:@book, local:true do |f|%>
        <p>title</p>
        <%= f.text_field :title,autofocus:true %>
        <p>body</p>
        <%= f.text_field :body ,autofocus:true %>
        <button type="submit" class="mt-3 btn btn-success btn-block">Create Book</button>
      <% end %>
    </div>
    <div class="col-md-8 col-xs-9 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-invers">
        <thead>
          <tr>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= attachment_image_tag book.user, :profile_image,:fill,40,40, fallback: "noimage.png",size:'40x40' %>
              <% end %>
            </td>
            <td>
              <%= link_to book.title , book_path(book) %>
            </td>
            <td><%= book.body %></td>
          <% if book.favorited_by?(current_user) %>
          <td>
            <%= link_to book_favorites_path(book) , method: :delete do %>
              <i class="fas fa-heart"></i><%= book.favorites.count %>
            <% end %>
          </td>
          <% else %>
          <td>
            <%= link_to book_favorites_path(book) ,method: :post do %>
              <i class="far fa-heart"></i><%= book.favorites.count %>
            <% end %>
          </td>
          <% end %>
          <td><%= link_to "コメント数:#{book.book_comments.count}",book_path(book) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% if flash[:notice]%>
  <%= flash[:notice] %>
<% end %>
<% if @book.errors.any? %>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--ログインしているユーザーの一覧情報-->
    <div class="col-md-3 col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag @books.user, :profile_image,:fill,100,100, fallback: "noimage.png",size:"100x100" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= @books.user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @books.user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <button type="button" class="btn btn-outline-primary btn-block">
          <%= link_to edit_user_path(@books.user) do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </button>
      </div>
      <h2 class="mt-3">New book</h2>
      <!--あとで修正をする-->
      <%= form_with model:@book, local:true do |f|%>
        <p>Title</p>
        <%= f.text_field :title,autofocus:true %>
        <p>Opinion</p>
        <%= f.text_field :body ,autofocus:true %>
        <button type="submit" class="mt-3 btn btn-success btn-block">Create Book</button>
      <% end %>
    </div>
    <div class="col-md-8 col-xs-9 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-invers">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@books.user) do %>
                <%= attachment_image_tag @books.user, :profile_image,:fill,40,40, fallback: "noimage.png",size:"40x40" %>
                <%= @books.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to @books.title , book_path(@books) %>
            </td>
            <td><%= @books.body %></td>
            <% if @books.favorited_by?(current_user) %>
            <td>
              <%= link_to book_favorites_path(@books),method: :delete do %>
                <i class="fas fa-heart"></i><%= @books.favorites.count %>
              <% end %>
            </td>
            <% else %>
            <td>
              <%= link_to book_favorites_path(@books),method: :post do %>
                <i class="far fa-heart"></i><%= @books.favorites.count %>
              <% end %>
            </td>
            <% end %>

            <td>コメント件数：<%= @books.book_comments.count %></td>
            <% if @books.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@books) %></td>
            <td><%= link_to "Destroy", book_path, method: :delete ,data: {confirm: '本当に削除しますか？'} %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <table  class="table table-hover table-invers">
        <tbody>
        <% @books.book_comments.each do |book_comment| %>
          <tr>
            <th><%= attachment_image_tag book_comment.user,:profile_image,:fill,40,40, fallback: "noimage.png",size:'40x40' %><%= book_comment.user.name %></th>
            <th><%= book_comment.comment %></th>
            <th><%= book_comment.created_at.strftime('%Y/%m/%d') %></th>
          <% if book_comment.user == current_user %>
            <th><%= link_to "delete" ,book_book_comment_path(book_comment.book,book_comment),method: :delete %></th>
          <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="container">
        <%= form_with(model:[@books,@book_comment], local: true) do |f| %>
        <div class="comment_form">
          <%= f.text_area :comment,placeholder: "write the comment here" %>
        </div>
        <div >
          <%= f.submit "Create Book comment" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="container col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0">
    <h1>welcome to<i class="fas fa-book"></i>Bookers !!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<main>
<%= flash[:notice] %>
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>welcome to <i class="fas fa-book"></i>bookers<strong>!!</strong></h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers,</strong><br/ >you can share and exchange your opinions , inpressions , and emotions<br />about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>


</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">

    <!--headerの作成-->
    <header class="shadow-sm">
      <nav class="navbar navbar-expand bg-dark ">
        <div class="container">
          <h1 class="text-white" >Bookers</h1>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-light', method: :get do %>
                <i class="fas fa-home" ></i>Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light', method: :get do %>
                <i class="fas fa-users"></i>Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-light', method: :get do %>
                <i class="fas fa-book-open"></i>Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, class: 'nav-link text-light', method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>logout
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-light', method: :get do %>
                <i class="fas fa-home" ></i>Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to home_about_path, class: 'nav-link text-light', method: :get do %>
                <i class="fas fa-link"></i>about
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light', method: :get do %>
                <i class="fas fa-user-plus"></i>sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light', method: :get do %>
                <i class="fas fa-sign-in-alt"></i>login
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>


    <!--mainの作成-->
    <main>
      <%= yield %>
    </main>

    <!--footerの作成-->
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<div class="containar">
  <div class="row">
    <div class="container col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0">
      <h1>User info</h1>
      <div class="form-body p-4">
        <% if @user.errors.any? %>
          <%= @user.errors.count %>error prohibited this obj from being saved:
          <% @user.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= form_with model: @user, local:true do |f| %>
        <h3>Name</h3>
          <div class="input-group">
          <%= f.text_field :name, class:"form-control", placeholder:"name" %>
          </div>
        <h3>Image</h3>
          <div class="input-group">
            <%= f.attachment_field :profile_image, placeholder: "image" %>
          </div>
        <h3>Introduction</h3>
          <%= f.text_area :introduction, class:"form-control", placeholder:"introduction" %>
          <hr>
          <%= f.submit 'Update User', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% if flash[:notice]%>
  <%= flash[:notice] %>
<% end %>
<% if @book.errors.any? %>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--ログインしているユーザーの一覧情報-->
    <div class="col-md-3 col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag current_user, :profile_image,:fill,100,100,fallback: "noimage.png",size:'100x100'%>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= current_user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= current_user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <button type="button" class="btn btn-outline-primary btn-block">
          <%= link_to edit_user_path(current_user), class: 'nav-link', method: :get do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </button>
      </div>
      <h2 class="mt-3">New book</h2>
      <!--あとで修正をする-->
      <%= form_with model:@book, local:true do |f|%>
        <p>Title</p>
        <%= f.text_field :title,autofocus:true %>
        <p>Opinion</p>
        <%= f.text_field :body ,autofocus:true %>
        <button type="submit" class="mt-3 btn btn-success btn-block">Create Book</button>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1 col-xs-9">
      <h2>Users</h2>
      <table class=" table table-hover table-invers">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image,:fill,40,40,fallback: "noimage.png",size:'40x40' %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice]%>
  <%= flash[:notice] %>
<% end %>
<% if @book.errors.any? %>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--ログインしているユーザーの一覧情報-->
    <div class="col-md-3 col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image,:fill,100,100, fallback: "noimage.png" ,size:'100x100'%>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <button type="button" class="btn btn-outline-primary btn-block">
          <%= link_to edit_user_path(@user) do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </button>
      </div>
      <h2 class="mt-3">New book</h2>
      <!--あとで修正をする-->
      <%= form_with model:@book, local:true do |f|%>
        <p>Title</p>
        <%= f.text_field :title,autofocus:true %>
        <p>Opinion</p>
        <%= f.text_field :body ,autofocus:true %>
        <button type="submit" class="mt-3 btn btn-success btn-block">Create Book</button>
      <% end %>
    </div>
    <div class="col-md-8 col-xs-9 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-invers">
        <thead>
          <tr>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= attachment_image_tag book.user, :profile_image,:fill,40,40, fallback: "noimage.png",size:'40x40' %>
              <% end %>
            </td>
            <td>
              <%= link_to book.title , book_path(book) %>
            </td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>